# -*- coding: utf-8 -*-
"""Laptop_price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A_ON_BORf-lUTXSN8iIch4TxZGW0qXqe
"""

import re
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import r2_score,root_mean_squared_error
from sklearn.preprocessing import LabelEncoder,StandardScaler, OrdinalEncoder , OneHotEncoder
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV
from xgboost import XGBRegressor
from sklearn import tree
from xgboost import plot_tree
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from scipy import stats
from sklearn.model_selection import learning_curve
from sklearn.metrics import mean_absolute_error, mean_squared_error

from google.colab import files
uploaded = files.upload()

pd.options.display.max_columns=None
pd.options.display.max_rows=None
df=pd.read_csv('laptop.csv')
df.head(10)

df.describe()

df.isnull().sum()

df.drop('Unnamed: 0',axis=1,inplace=True)
df.dropna(inplace=True)

"""Feature Extraction"""

#----------------modification of the resulution-----------------------------
df['Xresolution']=df['ScreenResolution'].str.extract(r'(\d+)x')[0].astype(float)
df['Yresolution']=df['ScreenResolution'].str.extract(r'x(\d+)')[0].astype(float)
df['Aspect resolution']=(df['Xresolution'] / df['Yresolution']).round(2)

#---------------------------Chaniging the screenResulution strings to the int------------------------
df['IPS']=df['ScreenResolution'].str.contains('IPS').astype(int)
df['Full HD']=df['ScreenResolution'].str.contains('Full HD').astype(int)
df['Touchscreen']=df['ScreenResolution'].str.contains('Touchscreen').astype(int)
df['Retina'] = df['ScreenResolution'].str.contains('Retina').astype(int)
df['4K'] = df['ScreenResolution'].str.contains('4K').astype(int)
df["QuadHD"] = df["ScreenResolution"].str.contains("Quad HD").astype(int)
df["Retina"] = df["ScreenResolution"].str.contains("Retina").astype(int)
df.drop('ScreenResolution',axis=1,inplace=True)
df.drop(['Xresolution','Yresolution'], axis=1, inplace=True)

#-------------------------------Changing in the CPU--------------------
df['CPU_Brand']=df['Cpu'].apply(lambda x: x.split()[0])
df['CPU_series']=df['Cpu'].apply(lambda x:" ".join(x.split()[1:3]))
df['Clock_speed']=df['Cpu'].apply(lambda x:float(x.split()[-1].replace("GHz","")))
df.drop('Cpu',axis=1,inplace=True)

#-----------------------Changing in Ram---------------------
df['RAM']=df['Ram'].str.replace('GB',"")
df.drop('Ram',axis=1,inplace=True)

# ------------------ Modifying the Memory ------------------


df.reset_index(drop=True, inplace=True)


df["HDD"] = 0
df["SSD"] = 0
df["Hybrid"] = 0
df["Flash"] = 0

def Convert_to_GB(value):
    value = value.upper().replace(" ", "")
    if "TB" in value:
        return float(value.replace("TB", "")) * 1000
    if "GB" in value:
        return float(value.replace("GB", ""))
    else:
     return 0


for i, entry in enumerate(df["Memory"]):
    if entry == "?" or entry.strip() == "":
        continue

    parts = entry.split("+")
    for part in parts:
        part = part.strip().upper()

        if "HDD" in part:
            size = part.replace("HDD", "")
            df.at[i, "HDD"] += Convert_to_GB(size)
        elif "SSD" in part:
            size = part.replace("SSD", "")
            df.at[i, "SSD"] += Convert_to_GB(size)
        elif "HYBRID" in part:
            size = part.replace("HYBRID", "")
            df.at[i, "Hybrid"] += Convert_to_GB(size)
        elif "FLASH" in part:
            size = part.replace("FLASH", "").replace("STORAGE", "")
            df.at[i, "Flash"] += Convert_to_GB(size)

df.drop("Memory", axis=1, inplace=True)

#------------------------------changing in the GPU-----------------
df["GPU_Brand"]=df['Gpu'].apply(lambda x:x.split()[0])
df["GPU_Series"] = df["Gpu"].apply(lambda x: " ".join(x.split()[1:]))
df.drop('Gpu',inplace=True,axis=1)
df["Type"]=df['TypeName'].str.replace("2 in 1",'')
df.drop('TypeName',axis=1,inplace=True)
df["weight"]=df["Weight"].str.replace('kg','')
df.drop("Weight",axis=1,inplace=True)

#---------------------removing the invalid values-----------------
df.drop('IPS',inplace=True,axis=1)
df.drop('QuadHD',inplace=True,axis=1)
df.drop('Hybrid',inplace=True,axis=1)
df.replace("?", np.nan, inplace=True)
df.replace("", np.nan, inplace=True)
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

"""Dataset after cleaning data"""

df.head()

#--------------------Seperating features and Target------------------------------
x=df.drop('Price',axis=1)
y=df['Price'].values
Y=np.log(y)

#-----------------------------Transforming  Values------------------------

vals=['Company','OpSys','CPU_Brand','CPU_series','GPU_Brand','GPU_Series','Type']
encoders = {}
le=LabelEncoder()
for i in vals:
   x[i]=le.fit_transform(x[i])

X=x.values
X

#----------------------Splitting  testing data------------------
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,train_size=0.8,random_state=42)

#---------------------scaling the values-------------------------
X_scalar=StandardScaler()
X_train_scaled=X_scalar.fit_transform(X_train)
X_test_scaled=X_scalar.transform(X_test)

"""# Supervised Algorithms

# Support Vector Regressor
"""

model_0 = SVR(kernel='rbf')
model_0.fit(X_train_scaled,Y_train)
y_pred_test=model_0.predict(X_test_scaled)
y_pred_train=model_0.predict(X_train_scaled)
print("------------SVM----------------")
print("r2_test",r2_score(Y_test,y_pred_test))
print("r2_train",r2_score(Y_train,y_pred_train))

"""# Linear Regression"""

model_1 = LinearRegression()
model_1.fit(X_train_scaled, Y_train)
y_pred_test=model_1.predict(X_test_scaled)
y_pred_train=model_1.predict(X_train_scaled)
print("---------Linear Regression-----------")
print("r2_test",r2_score(Y_test,y_pred_test))
print("r2_train",r2_score(Y_train,y_pred_train))

"""# Xtreme Boost Regressor"""

model=XGBRegressor(n_estimators=300, learning_rate=0.005, max_depth=5,min_child_weight= 1,subsample= 0.7, random_state=42)
model.fit(X_train_scaled,Y_train)
y_pred_test=model.predict(X_test_scaled)
y_pred_train=model.predict(X_train_scaled)
print("---------XGBOOST------------")
print("r2_test",r2_score(Y_test,y_pred_test))
print("r2_train",r2_score(Y_train,y_pred_train))

# ----------------------------Cheaking the best parameters--------------------------------
data={
   'n_estimators': [100, 200, 300],
    'subsample': [0.7, 0.8, 1.0],
    'learning_rate': [0.01, 0.05, 0.1],
    'objective': ['reg:squarederror'],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'max_depth': [3, 5, 8, 10]
}
cv=GridSearchCV(
   estimator=XGBRegressor(random_state=42),param_grid=data,cv=2,n_jobs=-2,scoring='r2'
)
cv.fit(X_train_scaled,Y_train)
print("Best parameters :",cv.best_params_)
print("Best Score : ",cv.best_score_)

#----------------------Cross Validation--------------------------------------------
scores = cross_val_score(model, X, Y, cv=5, scoring='r2')
print(scores)
print("Mean R²:", scores.mean())

models = {
    "SVR":               model_0,
    "Linear Regression": model_1,
    "XGBoost":           model,
}

preds_test  = {name: m.predict(X_test_scaled)  for name, m in models.items()}
preds_train = {name: m.predict(X_train_scaled) for name, m in models.items()}

r2_test  = {name: r2_score(Y_test,  preds_test[name])  for name in models}
r2_train = {name: r2_score(Y_train, preds_train[name]) for name in models}


fig, axes = plt.subplots(2, 3, figsize=(16, 10))
fig.suptitle("Model Comparison — Laptop Price Prediction", fontsize=15, fontweight='bold', y=1.01)

colors = {"SVR": "#378ADD", "Linear Regression": "#BA7517", "XGBoost": "#1D9E75"}

for ax, (name, y_pred) in zip(axes[0], preds_test.items()):
    ax.scatter(Y_test, y_pred, alpha=0.5, s=25, color=colors[name], edgecolors='none')
    lims = [min(Y_test.min(), y_pred.min()), max(Y_test.max(), y_pred.max())]
    ax.plot(lims, lims, 'k--', linewidth=1, label='Perfect fit')
    ax.set_title(f"{name}\nR² = {r2_test[name]:.4f}", fontsize=11, fontweight='bold')
    ax.set_xlabel("Actual log(Price)")
    ax.set_ylabel("Predicted log(Price)")
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)


for ax, (name, y_pred) in zip(axes[1], preds_test.items()):
    residuals = Y_test - y_pred
    ax.scatter(y_pred, residuals, alpha=0.5, s=25, color=colors[name], edgecolors='none')
    ax.axhline(0, color='black', linewidth=1, linestyle='--')
    ax.set_title(f"{name} — Residuals", fontsize=11, fontweight='bold')
    ax.set_xlabel("Predicted log(Price)")
    ax.set_ylabel("Residual")
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("model_comparison.png", dpi=150, bbox_inches='tight')
plt.show()

fig2, ax = plt.subplots(figsize=(8, 5))
names  = list(models.keys())
x      = np.arange(len(names))
width  = 0.35

bars1 = ax.bar(x - width/2, [r2_train[n] for n in names], width, label='Train R²',
               color=[colors[n] for n in names], alpha=0.9)
bars2 = ax.bar(x + width/2, [r2_test[n]  for n in names], width, label='Test R²',
               color=[colors[n] for n in names], alpha=0.45, edgecolor='gray')

for bar in bars1:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f"{bar.get_height():.3f}", ha='center', va='bottom', fontsize=9)
for bar in bars2:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f"{bar.get_height():.3f}", ha='center', va='bottom', fontsize=9)

ax.set_xticks(x)
ax.set_xticklabels(names, fontsize=11)
ax.set_ylabel("R² Score")
ax.set_title("Train vs Test R² — All Models", fontsize=13, fontweight='bold')
ax.legend()
ax.set_ylim(0, 1.05)
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig("r2_comparison.png", dpi=150, bbox_inches='tight')
plt.show()

print(f"\n{'Model':<22} {'Train R²':>10} {'Test R²':>10} {'Overfit Gap':>12}")
print("-" * 56)
for name in names:
    gap = r2_train[name] - r2_test[name]
    print(f"{name:<22} {r2_train[name]:>10.4f} {r2_test[name]:>10.4f} {gap:>12.4f}")

metrics = {}
for name, y_pred in preds_test.items():
    metrics[name] = {
        "R²":   r2_score(Y_test, y_pred),
        "RMSE": np.sqrt(mean_squared_error(Y_test, y_pred)),
        "MAE":  mean_absolute_error(Y_test, y_pred),
    }

metric_names = ["R²", "RMSE", "MAE"]
fig, axes = plt.subplots(1, 3, figsize=(14, 5))
fig.suptitle("Test Set Metrics — All Models", fontsize=14, fontweight='bold')

for ax, metric in zip(axes, metric_names):
    vals   = [metrics[n][metric] for n in names]
    bars   = ax.bar(names, vals, color=[colors[n] for n in names], alpha=0.85, width=0.5)
    for bar, v in zip(bars, vals):
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.002,
                f"{v:.4f}", ha='center', va='bottom', fontsize=9)
    ax.set_title(metric, fontsize=12, fontweight='bold')
    ax.set_ylabel(metric)
    ax.grid(axis='y', alpha=0.3)
    ax.tick_params(axis='x', rotation=10)

plt.tight_layout()
plt.savefig("metrics_comparison.png", dpi=150, bbox_inches='tight')
plt.show()

feature_names = list(x.columns)
importances   = model.feature_importances_
sorted_idx    = np.argsort(importances)

fig, ax = plt.subplots(figsize=(9, 7))
bars = ax.barh(
    [feature_names[i] for i in sorted_idx],
    importances[sorted_idx],
    color="#1D9E75", alpha=0.85
)
for bar, v in zip(bars, importances[sorted_idx]):
    ax.text(bar.get_width() + 0.001, bar.get_y() + bar.get_height()/2,
            f"{v:.3f}", va='center', fontsize=9)

ax.set_xlabel("Importance Score", fontsize=11)
ax.set_title("XGBoost — Feature Importance", fontsize=13, fontweight='bold')
ax.grid(axis='x', alpha=0.3)
plt.tight_layout()
plt.savefig("feature_importance.png", dpi=150, bbox_inches='tight')
plt.show()